config/routes.rb
SampleApp::Application.routes.draw do

  resources :orders
  resources :line_items
  resources :carts

  get "store/index"

  resources :products
  resources :users do
    member do     
      get :following, :followers
    end
  end   
  
  resources :sessions,       :only => [:new, :create, :destroy]
  resources :microposts,     :only => [:create, :destroy]
  resources :relationships,  :only => [:create, :destroy]  
  resources :prelationships, :only => [:create]
  resources :plants   
  resources :projects do        
    member do
       get :pfollowing, :pfollowers, :instructions  
    end
  end
  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", 'http://news.railstutorial.org/' %></li>
      <li><%= link_to "Rails Tutorial", 'http://railstutorial.org/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag("GardenZing Logo.png"), root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'colorbox', :media => 'screen' %>    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>    
<%= stylesheet_link_tag 'south-street/jquery-ui-1.8.16.custom.css', 
    :media => 'screen' %>    
<%= stylesheet_link_tag 'depot', :media => 'screen' %>  
<%= stylesheet_link_tag 'circles', :media => 'screen' %>
<%= stylesheet_link_tag 'circles',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->  
<%= stylesheet_link_tag 'colorbox', :media => 'screen' %>   
<%= stylesheet_link_tag 'custom', :media => 'screen' %>  
<%= stylesheet_link_tag 'south-street/jquery-ui-1.8.16.custom.css', 
    :media => 'screen' %> 
<%= stylesheet_link_tag 'depot', :media => 'screen' %> 
<%= stylesheet_link_tag 'circles', :media => 'screen' %>
<%= stylesheet_link_tag 'circles',  :media => 'print' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %> 
    <%= javascript_include_tag 'jquery.min', 'jquery_ujs',
    'jquery-ui', 'jquery.colorbox-min', 
    'jquery.listselect', 'jquery-ui-1.8.16.custom.min', 'application' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
	<div id="columns">  
	  <div id="side">
	    <div id="cart">  
		  <% if @cart %>    
		    <%= hidden_div_if(@cart.line_items.empty?, :id => 'cart') do %>
	          <%= render @cart %>
	        <% end %>        
	      <% end %>
	    </div>                                                          
	  </div> 
	</div>
  </body>   
</html>